### ISSUE TITLE
Query using geopoints returns bogus results

### ISSUE THREAD

**Issue by ldjpr** [andrewscofield/parse.com-php-library#10]
I am using the recent lib and executing a simple query using geo points. The returns are points that are thousands of miles apart very far from the search points. Any ideas on this?  This is the code.

$parse = new parseRestClient(array(
        'appid' => 'xxx',
        'restkey' => 'xxx'
));

$params = array(
        'className' => 'xxx',
        'geo' => array(
        '$nearSphere' => array(
            '__type'=> 'GeoPoint', 'latitude' => 43.3529, 'longitude' => 11.073, '$maxDistanceInKilometers' => '10')),
        'order' => 'business_name',
        'limit' => '100');
    $request = $parse->query($params);
    echo $request;

thanks

**Comment by FredvanRijswijk** [comment]
```
$params = array(
        'className' => 'XXX',
        'query' => array(
            'location'=> array(
                '$nearSphere' => array(
                    '__type' => 'GeoPoint',
                    'latitude' => 43.3529,
                    'longitude' => 11.073
                ),
                '$maxDistanceInKilometers' => 10
            )

        ),

        'limit' => '100'    
        );

    $request = $parse->query($params);
        echo $request;
```

**Comment by Moonkin-dk** [comment]
How would i go about doing such a query with parseQuery today?

Thx in advance
