### ISSUE TITLE
problem with parseQuery, ignoring setLimit when there is no query at all

### ISSUE THREAD

**Issue by zaherg** [andrewscofield/parse.com-php-library#103]
the problem is this, starting from line 36 (https://github.com/apotropaic/parse.com-php-library/blob/master/parseQuery.php#L36) if you dont have any where in your quert you will not be able to use things such as `setLimit` , `setSkip` or `order` so i think you should change it to : 

``` php
public function find(){
        $requestArray = array(
                'method' => 'GET',
                'requestUrl' => $this->_requestUrl
            );

            if(!empty($this->_query)){
                $urlParams = array(
                    'where' => json_encode( $this->_query )
                );
            }

            if(!empty($this->_include)){
                $urlParams['include'] = implode(',',$this->_include);
            }
            if(!empty($this->_order)){
                $urlParams['order'] = implode(',',$this->_order);
            }

            if(!empty($this->_limit) || $this->_limit == 0){
                $urlParams['limit'] = $this->_limit;
            }

            if(!empty($this->_skip)){
                $urlParams['skip'] = $this->_skip;
            }
            if($this->_count == 1){
                $urlParams['count'] = '1';
                // $urlParams['limit'] = '0';
            }
            if(!empty($this->_keys)){
                $urlParams['keys'] = $this->_keys;
            }

            $requestArray['urlParams'] = $urlParams;

            $request = $this->request($requestArray);

            return $request;
}
```

and i hope you can add this small function to add the `keys` to the query whenever they use it: 

``` php
    public function setKeys($keys){
        $this->_keys = $keys;
    }   
```

and this one for combound query, i know its not the best one to be use:

``` php
    public function whereCompound($value){
        if(isset($value) && is_array($value)){
            $this->_query['$or'] = $value;
        }   
        else{
            $this->throwError('the $value parameters must be set when setting a "whereCompound" query method');     
        }

    }
```

i was going to send you a pull request but my version is start to be differ from the one you have ( and am so happy to talk to you about it, since you ignore the `sessionToken` completely which by the way reflect on the permissions to for the roles).

**Comment by andrewscofield** [comment]
These all look like great change I should be able to implement. 

Also, I would love to see that pull request, if nothing else to see what you are talking about for the `sessionToken` that I am ignoring

**Comment by zaherg** [comment]
in parse.com you have the request to be like this : 

``` php
        if(substr($args['requestUrl'],0,5) == 'files'){
            curl_setopt($c, CURLOPT_HTTPHEADER, array(
                'Content-Type: '.$args['contentType'],
                'X-Parse-Application-Id: '.$this->_appid,
                'X-Parse-Master-Key: '.$this->_masterkey
            ));
            $isFile = true;
        }
        else if(substr($args['requestUrl'],0,5) == 'users' && isset($args['sessionToken'])){
            curl_setopt($c, CURLOPT_HTTPHEADER, array(
                'Content-Type: application/json',
                'X-Parse-Application-Id: '.$this->_appid,
                'X-Parse-REST-API-Key: '.$this->_restkey,
                'X-Parse-Session-Token: '.$args['sessionToken']
            ));
        }
        else{
            curl_setopt($c, CURLOPT_HTTPHEADER, array(
                'Content-Type: application/json',
                'X-Parse-Application-Id: '.$this->_appid,
                'X-Parse-REST-API-Key: '.$this->_restkey,
                'X-Parse-Master-Key: '.$this->_masterkey
            )); 
        }
```

and your code, the sessionToken will be used only with users class ..
lets say that i have a role called `Admin` and only those `users` from `Admin` role can create a new record for `products` ..
since you have suply the `X-Parse-Master-Key` everything will be ignored and any one can create a new records for `products` but if you make it like this : 

``` php
        if(substr($args['requestUrl'],0,5) == 'files'){
            curl_setopt($c, CURLOPT_HTTPHEADER, array(
                'Content-Type: '.$args['contentType'],
                'X-Parse-Application-Id: '.$this->_appid,
                'X-Parse-Master-Key: '.$this->_masterkey
            ));
            $isFile = true;
        }
        else if(isset($args['sessionToken'])){

            curl_setopt($c, CURLOPT_HTTPHEADER, array(
                'Content-Type: application/json',
                'X-Parse-Application-Id: '.$this->_appid,
                'X-Parse-REST-API-Key: '.$this->_restkey,
                'X-Parse-Session-Token: '.$args['sessionToken']
            ));
        }       
        else{
            curl_setopt($c, CURLOPT_HTTPHEADER, array(
                'Content-Type: application/json',
                'X-Parse-Application-Id: '.$this->_appid,
                'X-Parse-REST-API-Key: '.$this->_restkey,
                'X-Parse-Master-Key: '.$this->_masterkey
            )); 
        }
```

then it will use the `sessionToken` to validate the user credential (am not saying its the best code yet)

**Comment by zaherg** [comment]
about the pull, you know it , the one with the config changes ..
this one https://github.com/apotropaic/parse.com-php-library/pull/94 with those changes

**Comment by andrewscofield** [comment]
Ahh, yes, I do remember those config change discussions! 

Well I actually have no problems with using `sessionToken` in this way, makes total sense. I just haven't used ACL a whole lot, so its not that I was ignoring it, more like I didn't realize people were using it in this way. Glad you brought it to my attention though.

**Comment by andrewscofield** [comment]
Hey can you point me to the docs where _keys would be used in parseQuery? Never seen that one before.

Also as for your original request in this discussion, it was patched already here https://github.com/apotropaic/parse.com-php-library/pull/95

**Comment by zaherg** [comment]
1- for the keys

```
You can restrict the fields returned by passing keys a comma-separated list. To retrieve documents that contain only the score and playerName fields (and also special built-in fields such as objectId, createdAt, and updatedAt):

 --data-urlencode 'keys=score,playerName' \
  https://api.parse.com/1/classes/GameScore
```

its the last one in https://www.parse.com/docs/rest#queries-constraints

2- for the original request in (https://github.com/apotropaic/parse.com-php-library/blob/a3d1c1f03f6cc8de8f12c1156afc3813a03ccc45/parseQuery.php) 
if you read the code again, you will notice that you ignore everything if the query is empty ..
so if for example i want to bring the first `10` records , i must use `where` to make the `setLimit` work ..

**Comment by o-zhilin** [comment]
I am sorry, but I do not understand, how to use group by (Mysql analogue)? I Want  get some activity and join product and user classes, my results is not fine;
Example code:
            $q1 = new parseQuery('Product');
            $q2 = new parseQuery('Views');
            $q2->wherePointer('userId', '_User', $this->currentUserId);
            $q2->whereInclude('productId');
            $q2->setLimit(4);
            $this->view->viewProducts = $q2->find()->results;

If I did not write in the subject please do not ignore because I have problems with English, if this has already been discussed please provide a link to the problem or the documentation. Thank you for understanding.

**Comment by zaherg** [comment]
@o-zhilin in simple English, Parse.com does not support `group by` since its based on noSQL.

**Comment by o-zhilin** [comment]
If you are not burdensome, please tell me the solution?

**Comment by zaherg** [comment]
sorry there is no simple solution for this ( https://www.parse.com/questions/group-by-distinct) best if you check the relations docs https://www.parse.com/docs/relations_guide

**Comment by o-zhilin** [comment]
Thank you very much for your help, I will understand.
