### ISSUE TITLE
how to insert a row in a particular class (table)?

### ISSUE THREAD

**Issue by satheesh110** [andrewscofield/parse.com-php-library#141]
I've successfully retrieved data from parse.com, thank you so much for your great work. I'm struck here.  I've searched everywhere I couldn't find even a single example how to insert a row of data in a specified table and update it. Just a simple example.Your answer will help many others too. Help me out please! INSERT and UPDATE

**Comment by jay-neb** [comment]
If you look at `parseObject.php` it's pretty clear, but here's an example:

```
$parseObject = new parseObject($className);
$parseObject->col1 = $col1Value;
$parseObject->col2 = $col2Value;
// etc.

// to create:
$parseObject->save();

// to update:
$parseObject->update($objectId);
```

To insert/update users have a look at `parseUser.php`, it's very similar with some small differences.

**Comment by satheesh110** [comment]
Thank you soooo much! I get it.
