### ISSUE TITLE
Do you accept pull requests?

### ISSUE THREAD

**Issue by scarstens** [andrewscofield/parse.com-php-library#147]
I would like to know if you are active on this project or not. I have built a parseBatch.php extension for your parseObject.php class. I've already tested it and have it in production. Before I go through the hassel of sending you pull requests, I want to make sure you will consider them.

**Comment by andrewscofield** [comment]
I am only semi active right now, due to life + work. I'm looking forward to getting back into this project as soon as things slow down. So, yes any help you'd like to contribute would be great and a pull request can easily be seen by other developers.

**Comment by kublermdk** [comment]
I've seen active replies to this repo with help and changes, although I've
only been watching it and haven't seen any pull requests I think it would

## be worth creating one.

Michael Kubler
Mob : 0433 483 008

"Activism is not a spectator sport"
