### ISSUE TITLE
Get the user information from the creator behind a post

### ISSUE THREAD

**Issue by andyafonso** [andrewscofield/parse.com-php-library#15]
Hi, i'm currently working on a mobile application that has enabled sharing on facebook.

When i'm on facebook and clicks on a shared post from the mobile application i get to a link containing a specific objectId that retrieves the posts information. The information contains pictures, texts and so on.

In my php script on the webpage i use the method get like this:

$params = array( 'className' => 'Feed', 'objectId' => $_GET['id'] );
$request = $parse->get($params);
$result = json_decode($request);

So far so good, but what if i want to include the user information of the user that created this post? That information is stored in another table called 'User'. I have struggled with this for a long time. 

If someone can give me a lead on what to do i would be greatful :)

Thanks alot.

**Comment by andrewscofield** [comment]
Hey, so my php library currently doesn't support the User table on parse. I'm am actively working on a new version of the library that supports all the features parse has to offer through their REST API. Check back soon!
