### ISSUE TITLE
Hi, apotropaic

### ISSUE THREAD

**Issue by brunojasgv** [andrewscofield/parse.com-php-library#16]
Hi, i would like to make a user login form in PHP to post images, videos and files for specific users,  can you provide more info about new methods to be used to accomplish these tasks? Are there any more advance examples to have a friendly user interface for the parse REST API?

Best Regards.

**Comment by andrewscofield** [comment]
Hi, this currently isn't possible with this version of php library. I am however working on a new version of the library that I will be pushing up to github soon. Check back soon for that update, should be easier to accomplish something like what you are talking about.
