### ISSUE TITLE
Modified For Drupal

### ISSUE THREAD

**Issue by ElusiveMind** [andrewscofield/parse.com-php-library#171]
I have made a number of modifications to get this to work in Drupal with a module I am working on. I would like to ultimately contrib this module to Drupal.org but would need to include my version of the library. Please let me know if this is a problem.

**Comment by andrewscofield** [comment]
Not a problem for me. Do you need me to do anything?

FYI, I was about 90% done with a major update on this library when parse
announced their own php library. I kind of stopped working on it.

---

Andrew Scofield

## Creative Team Leader • Web Director

Jesus Culture
jesusculture.com

**Comment by ElusiveMind** [comment]
Yeah the only issue is is there a library requires PHP 5.4 which is not an option for me right now

**Comment by andrewscofield** [comment]
Oh I see. I do have an older version  (v1) that doesn't require php5.4. Sounds like you already got things figure out though.

https://github.com/apotropaic/parse.com-php-library/tree/parse.com-php-library_v1
