### ISSUE TITLE
Relational queries - is there a way to use $inquery?

### ISSUE THREAD

**Issue by johnrisby** [andrewscofield/parse.com-php-library#19]
Hi,

Thanks for the library. 

Is there a way to use relational queries (see https://parse.com/docs/rest#queries-relational) using the library? Particularly sub-queries that would use $inquery operator via curl.

Thanks
John

**Comment by johnrisby** [comment]
Hi,

Does anyone know the answer to this please?

Thanks
John

**Comment by andrewscofield** [comment]
Hey John, sorry for the late response. I've been away for a little bit and just now getting back to this project. There currently isn't a way to use $inquery. I'm working on version 2 of this api library that does have this feature.
