### ISSUE TITLE
Failed to get response 201 when trying to create an object with GeoPoint

### ISSUE THREAD

**Issue by ldjpr** [andrewscofield/parse.com-php-library#2]
Hello
$parse = new parseRestClient(array('appid' => 'xxx, 'masterkey' => 'xxx'));

I am receiving the error in title. Here is the code.

$params = array(
        'className' => 'class_name',
        'object' => array(
            'geo' => array('__type' => 'GeoPoint', 'latitude' => '43.35', 'longitude' => '11.0'),
            'name' => 'my house'));

$request = $parse->create($params);

Can anyone help me with this? It works well if i remove the geo key.

thanks

ldj

**Comment by andrewscofield** [comment]
The problem here is the lat & long are being passed as strings, remove the single quotes there and should work for you.

Please check out my most recent changes for some fixes and updates.
