### ISSUE TITLE
Attachments, etc.

### ISSUE THREAD

**Issue by ghost** [andrewscofield/parse.com-php-library#20]
Hi!

We used your base and greatly modded from there.  Have you done attachments yet?

We can do it via curl at the command line - but are working to integrate it w/ php.  If you don't have something, I'll post inline as a response when we get it working today.

BTW, there is a user handler class for Java over in my repo.

**Comment by andrewscofield** [comment]
Hi Jack sorry for the delay, I've been away for a while but am finally making it back to this project. I am working on v2 of this project and it does include attachments. In fact it actually includes every REST functionality made available by parse. I'll be pushing first beta soon on this repo. 

I would love to see your implementation of the attachments though!
