### ISSUE TITLE
Performing create using Ints

### ISSUE THREAD

**Issue by vincentjr** [andrewscofield/parse.com-php-library#22]
Does this API support using ints? For example, submitting a number to a Parse class with an int column.

When I use the create API, it will eventually call the request function and perform a json_encode on the payload. This causes the variable to equal something like this:

{"idNumberOne":"Clol67k","intColumnA":"12","intColumnB":"5","stringColumn":"90"}

I'm seeing ERROR: response code was 400 with message: invalid type for key intColumnA, expected number, but got string

I believe what is happening is it's interpreting the quotes. The $postData should look something like:

{"idNumberOne":"Clol67k","intColumnA":12,"intColumnB":5,"stringColumn":"90"}   <----- No quotes around the numbers

Being that we are using json_encode this is going to be a difficult problem to solve.... Any suggestions?

Also, I added login and register functionality to the API. Should I push something to somewhere? :D
- Vin

**Comment by andrewscofield** [comment]
Hey! What version of PHP are you using? My json_encode outputs integers with no problems. Try running this test found on the answer here:

http://stackoverflow.com/questions/1390983/php-json-encode-encoding-numbers-as-strings

and see if you get back integers or strings.

**Comment by vincentjr** [comment]
I will look into this when I get home. Thanks for the response!

On Mon, Jul 23, 2012 at 12:44 AM, apotropaic <
reply@reply.github.com

> wrote:
> 
> Hey! What version of PHP are you using? My json_encode outputs integers
> with no problems. Try running this test found on the answer here:
> 
> http://stackoverflow.com/questions/1390983/php-json-encode-encoding-numbers-as-strings
> 
> and see if you get back integers or strings.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/apotropaic/parse.com-php-library/issues/22#issuecomment-7172132

## 

Regards,

Vincent Smith
vinny.smith@gmail.com

**Comment by vincentjr** [comment]
PHP Version: 5.3.6

After adding JSON_NUMERIC_CHECK to:
 if($args['method'] == 'PUT' || $args['method'] == "POST"){
    $postData = json_encode($args['payload'], JSON_NUMERIC_CHECK);

It now works as intended. Thank you.

**Comment by andrewscofield** [comment]
Good to hear!
