### ISSUE TITLE
Exceptions instead of die

### ISSUE THREAD

**Issue by jobrienski** [andrewscofield/parse.com-php-library#24]
Hi apotropaic, when you're writing the new version, can you use exceptions?  I'd rather catch an exception, rather than have the program die.

**Comment by andrewscofield** [comment]
Yea, me too! Sorry this version was written in a couple hours and I was more just prototyping some stuff. I am actually using the new version for something real and also parse added a lot of features since I wrote this. New version should be up tonight.

**Comment by jobrienski** [comment]
Look forward to it!
