### ISSUE TITLE
Where do I begin?

### ISSUE THREAD

**Issue by bluesmokellc** [andrewscofield/parse.com-php-library#27]
I need a simple script that can send Wordpress posts to a Parse database. My usual PHP guy has disappeared on me and I need this done ASAP. Is there a tutorial or sample file I could look at? Or perhaps you could recommend someone I could hire?

**Comment by andrewscofield** [comment]
Are you trying to put all new posts or already existing posts to parse?

**Comment by bluesmokellc** [comment]
The posts are created in Wordpress. I just need a script that will update the Parse Database when a post is created or deleted. It could be just a cron job that wipes the slate clean every night and re-submits all of the posts.

**Comment by andrewscofield** [comment]
I might be able to do the work, it just depends on what you mean by ASAP :)

**Comment by andrewscofield** [comment]
Either way, the process is relatively simple. You write a function that takes a post_id and you use wordpress functions to get the title, content, etc. Then you would use the parseQuery class to first look for that post_id in parse, so we don't create duplicated. Then use the parseObject to add/edit the title, content fields. 

You can then use the function either in a cron job or use wordpress hooks to have it called anytime a post is added to updated or deleted.

I don't yet have tutorials :( You can check out this folder though to see how this library is supposed to work: 

https://github.com/apotropaic/parse.com-php-library/tree/2.0/master/tests

**Comment by bluesmokellc** [comment]
Is this something you could write in a couple of hours? I have to have
this done by the end of the day.

On Aug 3, 2012, at 1:02 AM, apotropaic
reply@reply.github.com
wrote:

**Comment by bluesmokellc** [comment]
Well, I still couldn't figure it out. How long would it take you to write a script? And what would it cost?

**Comment by andrewscofield** [comment]
I'm not sure I could even have it done this weekend. Got heavy workload right now. I was hoping you had a little more time then end of day. It would be probably take 2-3 hours to write the script itself but I would probably spend another couple hours just researching that I had all the right wordpress functionality sorted out and doing testing.

**Comment by bluesmokellc** [comment]
I definitely need it done before the end of the weekend. Would $200 be enough to get that done? Maybe you can recommend someone else to do it. I've already been let down by 3 different programmers who said they could do this for me. I really just want it off my plate.

**Comment by andrewscofield** [comment]
Sorry, I can't promise end of weekend at all. I'll give it a shot tomorrow and see what I can come up with, but I am thinking I don't have the time.

**Comment by bluesmokellc** [comment]
Thanks. I will continue to try and wrap my head around it.

**Comment by bluesmokellc** [comment]
It looks like we resolved the issue by creating a Wordpress plugin (by we, I mean this guy that I hired in the eleventh hour).

**Comment by andrewscofield** [comment]
Great to hear! I do think it could be a cool little wordpress plugin if was developed out to have a number of features.
