### ISSUE TITLE
Bug in parseQuery.

### ISSUE THREAD

**Issue by uhnomoli** [andrewscofield/parse.com-php-library#28]
Not sure if this was just a recent API change Parse.com's end that hasn't made it over yet, but on [line #30](https://github.com/apotropaic/parse.com-php-library/blob/2.0/master/parseQuery.php#L30) in parseQuery.php the `'query'` key in the `'urlParams'` array should be `'where'`.

**Comment by andrewscofield** [comment]
Hey, looks like your are right! Not sure how that happened. But it was verified here: https://parse.com/docs/rest#queries-constraints  

Fixed now in the latest commit
