### ISSUE TITLE
please help me with Image Upload

### ISSUE THREAD

**Issue by shihabshahriar** [andrewscofield/parse.com-php-library#29]
I want to upload a image via PHP to Parse , please help me how can I do it.

**Comment by andrewscofield** [comment]
Not 100% this will work but maybe try this:

```
$filename = '/path/to/image.jpg';

$file = parseFile('image/jpeg', file_get_contents($filename) ));
$save = $file->save('testimage.jpg'); //should return url and name

```

**Comment by shihabshahriar** [comment]
ok, thanks anyway , I will try let you know :)

**Comment by andrewscofield** [comment]
How did this work out for you?

**Comment by ghost** [comment]
not work, have anyway how to upload image?

**Comment by leonova** [comment]
upload successful but the image is not diplaying. it says error on content
