### ISSUE TITLE
 Trying to get property of non-object error

### ISSUE THREAD

**Issue by kjj1** [andrewscofield/parse.com-php-library#30]
Hi apotropaic,
and thanks for your library.

I'm having a (supposedly) very basic issue with your library (both version 1 and 2).
I just want to query all objects of the class ("Repairer" in parse.com data browser) and, after initializing lie this :

require ("parse/parse.php");
$parse = new parseRestClient(array(
'appid' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
'restkey' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
));

(with the correct keys of course; also, the parseConfig.php is correctly filled)

I just call a simple function to retrieve them :

function getRepairers() {
$query = new parseQuery('repairers');
$query->where('status', 0);
$request = $query->find();
return $request;

}
I get this notice (that I had in version 1 too) :

Notice: Trying to get property of non-object in E:\xampp\htdocs\parse\parse\parse.php on line 162

twice, and then this one :

Fatal error: Uncaught ParseLibraryException: [0]: thrown in E:\xampp\htdocs\parse\parse\parse.php on line 155

Apparently, the expected (HTTP) code is 200, but the received one is 0 (which is not a HTTP code as far as I know).
I understand I am missing something very basic, can you please tell me what ?

Thanks in advance

**Comment by andrewscofield** [comment]
One problem I see off that bat is that in version 2.0 you don't to initiate the parseRestClient, in other words you don't need this:

```

$parse = new parseRestClient(array(
'appid' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
'restkey' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
));
```

This could be causing some errors. Also, you will need to wrap your code in a try/catch to know what the error code is:

```

try {
getRepairers()
} catch (ParseLibraryException $e) {
    echo 'Caught parse exception: ',  $e->getMessage(), "\n";
}
```

This should tell you why parse is sending you back an http code of 0. They do that for a few different reasons. Hope this helps!

**Comment by kjj1** [comment]
Hi, and thanks for your fast answer !
I deleted the version 1 part and used a try/catch,
now I get :

Notice: Trying to get property of non-object in E:\xampp\htdocs\parse\parse\parse.php on line 162

Notice: Trying to get property of non-object in E:\xampp\htdocs\parse\parse\parse.php on line 162
Caught parse exception: 

with an empty exception. Does this ring any bell to you ?

**Comment by andrewscofield** [comment]
I have had a few people tell me that json_decode isn't working as expected for them. Can you go to line 162 and just above it add the line:

```
print_r($response);
```

so we can see what the response is and make sure it is JSON. If it is, we would need to figure out why json_decode isn't working on your server. Could be a php version thing?

**Comment by kjj1** [comment]
It's actually a testing server on localhost/parse, and I'm running  XAMPP 1.7.7 [PHP: 5.3.8](curl enabled of course)

The $response is empty too...

**Comment by kjj1** [comment]
It actually was a problem with the server, moving to live server proved to be effective

**Comment by andrewscofield** [comment]
Good to hear you got it working on your live server. If you figure out why it wasn't on working on your local XAMPP server, and its code related, please let me know!

**Comment by sideprojecteu** [comment]
I know it's closed but if anyone would have the same problem I managed to fix that on XAMPP.

Just replace this:
$response = curl_exec($c);

with that:
curl_setopt($c, CURLOPT_SSL_VERIFYPEER, false);
if(!$response = curl_exec($c)) {
   die(curl_error($c));
}
in parse.php file.

The response was empty because of some problem with SSL certificate validation on XAMPP side. Hope this helps.
