### ISSUE TITLE
Relational Query Example no longer valid

### ISSUE THREAD

**Issue by dr-impossible** [andrewscofield/parse.com-php-library#31]
I'm assuming this is probably due to some recent changes in the api, but it seems that the example you have posted in the README.md is no longer correct. It should look something more like this:

``` PHP
$params = array(
    'className' => 'User',
    'query' => array(
        'Post' => array(
            '__type' => 'Pointer',
            'className' => 'Post',
            'objectId' => $postId
        )
    )
);

$request = $parse->query($params);
```

**Comment by dr-impossible** [comment]
Oops, sorry, I was looking at the wrong type of query in the Parse.com docs. Please disregard this bug.

**Comment by andrewscofield** [comment]
Good to know! Thanks for posting this back here
