### ISSUE TITLE
Suggestions and Notes for v2.0

### ISSUE THREAD

**Issue by scottfr** [andrewscofield/parse.com-php-library#33]
Thanks for the great library! Some suggestions.
- setLimit function for Query should allow values of 1 and 1000. Should change comparison operators to equals-than or greater than.
- setStep function needed for Query.
- count function needed for Query to get total count of objects without returning them.
- The parse date data type should be converted to a PHP data type with the propoer time zone.
- The CURL timeout should be changed from 5 seconds to something larger like 30 seconds.

**Comment by scottfr** [comment]
Correction: setStep should be setSkip.

**Comment by andrewscofield** [comment]
These are all great suggestions... I'll try to get to them soon. If you get a chance, you could fork my repo and send some pull requests with some of these changes. Even getting me links to docs on the parse.com website for those parts would be quite helpful!
