### ISSUE TITLE
How can I update a specific object

### ISSUE THREAD

**Issue by liorwn** [andrewscofield/parse.com-php-library#34]
Hi,

This might seem like a stupid question but I couldn't figure out how to update a specific object.

I know the following doesn't work because it calls to a class instead of a specific object within a class (and POST instead of PUT) but I have no idea what to change in order to make it work:

$o = $_POST["objectId"];
$odoValue = intval($_POST["Value"]);

$parseObject = new parseObject('Cars');

$parseObject->VALUE = $Value;
$response = $parseObject->save();

What I'm trying to figure out is how to update the Field 'VALUE' for a specific objectId within the Class Cars.

Thanks in advance! Any help would be appreciated.

**Comment by andrewscofield** [comment]
Somewhere along the way from v1 to v2, I've lost my ability to update an object! Ooops :)

I've updated the library to include this ability, see example below:

```
$objectId = $_POST['objectId'];
$newValue = $_POST['Value'];

$parseObject = new parseObject('Cars');
$parseObject->VALUE = $newValue;
$return = $parseObject->update($objectId); //should return updatedAt date if successfull

```

let me know how this works... I just made it and only did a quick test on it.

**Comment by liorwn** [comment]
Perfect! Thanks so much. I was starting to think I'm getting delusional :)
