### ISSUE TITLE
How to query?

### ISSUE THREAD

**Issue by FredvanRijswijk** [andrewscofield/parse.com-php-library#35]
I want to test this version, but I get an error on the parseClient is missing "Class 'parseRestClient' not found" 

Can you give us a working example how to use the whole new parse php library

cheers Fred

**Comment by aricotta** [comment]
I had the same issue.  Adding the following 2 statements to the request function fixed it for me:

curl_setopt ($c,CURLOPT_SSL_VERIFYPEER, false);
curl_setopt ($c,CURLOPT_SSL_VERIFYHOST, false);

Hope it helps.

**Comment by andrewscofield** [comment]
Yea if you are for sure including or requiring in the library correctly and you are still getting this error, you have a core php error. Meaning the php config on your server itself is not liking something about this library. 

It seems the fix above does help on some server configurations. But in reality, you have to go into your php error logs to see why it fails to include/require the library.
