### ISSUE TITLE
Limit=1 problem

### ISSUE THREAD

**Issue by liorwn** [andrewscofield/parse.com-php-library#38]
Hey,

When I try to query using limit=1 the code just doesn't seem to work (throws an exception).

This works perfectly:

$parseQuery = new parseQuery('CLASS');
$parseQuery->where('STAT',1);
$parseQuery->orderByDescending('TIME');
$parseQuery->setLimit(2);
$response3 = $parseQuery->find();

While this is returning an exception (notice setLimit=1):

$parseQuery = new parseQuery('CLASS');
$parseQuery->where('STAT',1);
$parseQuery->orderByDescending('TIME');
$parseQuery->setLimit(1);
$response3 = $parseQuery->find();

Fatal error: Uncaught ParseLibraryException: [0]: parse requires the limit parameter be between 1 and 1000 thrown in /Applications/MAMP/htdocs//parse/parse.php on line 168

Ideas?

**Comment by liorwn** [comment]
Found the fix, I changed the setLimit code:

public function setLimit($int){
        if ($int > 1 && $int < 1000){
            $this->_limit = $int;
        }
        else{
            $this->throwError('parse requires the limit parameter be between 1 and 1000');
        }
    }

It should be >= and <=:

public function setLimit($int){
        if ($int >= 1 && $int <= 1000){
            $this->_limit = $int;
        }
        else{
            $this->throwError('parse requires the limit parameter be between 1 and 1000');
        }
    }

**Comment by andrewscofield** [comment]
Yep! This is for sure the problem. Fix being posted in a few mins. Thanks for this!

**Comment by liorwn** [comment]
Sure thing! Thanks for creating the wrapper :) It's really a big help.
