### ISSUE TITLE
add/remove relations

### ISSUE THREAD

**Issue by jobrienski** [andrewscofield/parse.com-php-library#39]
Hi apotropaic,
Thanks for the new version.  I like the interface much better.
Is there code in there to relate objects?  I don't think I see it but I could be missing it.
Thanks,
-jim

**Comment by andrewscofield** [comment]
If you mean doing this here: https://parse.com/docs/rest#queries-relational

Yea, its possible with this library, just maybe not a straight forward is it could/should be. Using their examples, you could do something like this: 

```
$parseQuery = new parseQuery('Comment');

// below just returns a specific formated array needed for a pointer query
$pointer = $parseQuery->dataType('pointer', array('post','8TOXdXf3tz'));

$post = $parseQuery->where('post', $pointer);
```

I haven't done much more then testing with this method. Let me know how it works for you... I'm all for making this library as useful and practical as possible.

**Comment by jobrienski** [comment]
Thanks.  Actually I meant adding a relation to an object.

**Comment by andrewscofield** [comment]
Oh, so I just looked up on parse.com docs and found that I maybe not have seen this functionality here: 

https://parse.com/docs/rest#container7

Or maybe its changed since I've started the library? Anyway, so no I don't have this built into a nice function, but I think you should be able to do it like this:

```
$parseObject = new parseObject('comment')
$parseObject->posts = array(
    '__op' => 'AddRelation',
    'objects' => array( 
        $parseQuery->dataType('pointer', array('post','8TOXdXf3tz')) 
        $parseQuery->dataType('pointer', array('post','Ed1nuqPvc')),
    )
);
```

Make sense? I do need to add this functionality into the library

**Comment by jobrienski** [comment]
Thanks, I'll give it a try.
-jim

**Comment by jobrienski** [comment]
You mean parseObject-> not parseQuery->?  Also the 'post' in the pointer is the tablename of the linked object?
Thanks,
-jim

```
$parseObject = new parseObject('comment')
$parseObject->posts = array(
    '__op' => 'AddRelation',
    'objects' => array( 
        $parseObject->dataType('pointer', array('post','8TOXdXf3tz')) 
        $parseObject->dataType('pointer', array('post','Ed1nuqPvc')),
    )
);
```

**Comment by jobrienski** [comment]
Ok that works.   I like the library much better.  I think it's more compact to develop with.

**Comment by andrewscofield** [comment]
Yea, just to answer the questions:

I did mean parseObject. Also, meant to add this line at the end:

```
$parseObject->save();
```

which would save that comment object with 'posts' field being a relational your object(s).

And yes 'post' is the class name  (as parse calls them, but technically they are tables) of the object you are adding a relational pointer to.
