### ISSUE TITLE
Creation of new object not working

### ISSUE THREAD

**Issue by willsr** [andrewscofield/parse.com-php-library#4]
When running this :

$query = ($_POST['query']) ? $_POST['query'] : $_GET['query'];

```
$params = array(
    'className' => 'temperature',
    'object' => array(
        'value' => $query

    )
);

$request = $parse->create($params);
```

I get this warning:

Warning: json_encode() expects exactly 1 parameter, 2 given in /home/corocco/public_html/parse.php on line 134
failed to get response 201, response code was: 400

and no new objects are created..

Any ideas?

**Comment by andrewscofield** [comment]
I think its because json_encode is a php5.3 only thing. If you take out the part that says JSON_NUMERIC_CHECK on line 134 it won't give you that error any more. But adding that line was a fix for another problem. This will work for you temporarily, I'll find another more compatible fix

**Comment by willsr** [comment]
Hi, 
Yep, that fix removed the warning, but I still get "failed to get response 201, response code was: 401"
when I try to create a new object with this code:

```
$params = array(
    'className' => 'temperature',
    'object' => array(
        'value' => '20'
    )
);

$request = $parse->create($params);
```

**Comment by andrewscofield** [comment]
Hey, I just made a few fixes, it looks like they changed the API authentication on me. Should work now.

Also, please read the README on git for a small change in how to create an object
