### ISSUE TITLE
Syntax errors: parseQuery.php

### ISSUE THREAD

**Issue by jobrienski** [andrewscofield/parse.com-php-library#41]
PHP Parse error:  syntax error, unexpected '}' in Downloads/apotropaic-parse.com-php-library-4b2e2ee/parseQuery.php on line 48

Fix:

```
                                $urlParams['count'] = '1';
```

PHP Parse error:  syntax error, unexpected T_DOUBLE_ARROW in Downloads/apotropaic-parse.com-php-library-4b2e2ee/parseQuery.php on line 67
Fix:

```
                if ($int >= 1 && $int <= 1000){
```

**Comment by andrewscofield** [comment]
Latest commit has these fixes. Thanks!
