### ISSUE TITLE
Update user?

### ISSUE THREAD

**Issue by jobrienski** [andrewscofield/parse.com-php-library#44]
I don't think it's in the parseUser.php class.  Can you update a user with additional fields or create a user with additional fields?

curl -X PUT \
  -H "X-Parse-Application-Id: Z0GKPdAmkIZsKg9nGgSGU52DQBUP2xavHmACYsAI" \
  -H "X-Parse-REST-API-Key: lOQHg18qhxveTkNA6YGIWDtwBpwQ9ULyK2ZwPqTh" \
  -H "X-Parse-Session-Token: pnktnjyb996sj4p156gjtp4im" \
  -H "Content-Type: application/json" \
  -d '{"phone":"415-369-6201"}' \
  https://api.parse.com/1/users/g7y9tkhB7O

Thanks,
-jim

**Comment by andrewscofield** [comment]
This is now possible with the latest commit: https://github.com/apotropaic/parse.com-php-library/commit/3a59af32b2e7846fcb215437156a179b87bdc8c3

Borrowing from you curl example above:

```
$parseUser = new parseUser;
$parseUser->phone = "415-369-6201";

$parseUser->update( 'g7y9tkhB7O', 'pnktnjyb996sj4p156gjtp4im'  ); //( objectId, Session-Token )
```

Hope that makes sense!

**Comment by jobrienski** [comment]
Awesome - thanks!

**Comment by leonova** [comment]
hi how did you get the Session-Token='pnktnjyb996sj4p156gjtp4im' ?
