### ISSUE TITLE
failed to get response

### ISSUE THREAD

**Issue by FredvanRijswijk** [andrewscofield/parse.com-php-library#5]
failed to get response 201, response code was: 0

or 

failed to get response 200, response code was: 0

are the errors I get?

**Comment by andrewscofield** [comment]
can you give me an example request you are trying to do when you get this error. I put that error message in place so I would know SOMETHING went wrong. Parse sends back certain response codes on success and others for errors, so this should lead to where the error is, but in your case the response code was 0 which is strange

**Comment by FredvanRijswijk** [comment]
ERROR: response code was 0 with message:

this is with the new code... 

<?php 

require_once("parse.php");

```
$parse = new parseRestClient(array(
    'appid' => 'xxxxxx',
    'restkey' => 'xxxxxx'
));

$params = array(
'className' => 'GameScore',
'objectId' => 'xAm2PlrgT4'
```

);

$request = $parse->get($params);

CURL is installed... Strange no errors...

?>

**Comment by FredvanRijswijk** [comment]
The problem is (solved)...

Added 

curl_setopt($c, CURLOPT_SSL_VERIFYPEER, false);

also edit 

$curlerror = curl_errno($c);

```
    return array('code'=>$httpCode, 'response'=>$response, 'error'=>$curlerror);
```

hopes it makes sense?

**Comment by andrewscofield** [comment]
great find! I'll update the repository soon

**Comment by warnew** [comment]
What's up with this fix? I have a similar problem, and can't find these lines in the code.
