### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by marcpar** [andrewscofield/parse.com-php-library#50]
hi Great api by the way version 1 and version 2 i could not work it in my localhost im using xampp 1.7.7 5.3.8 php 

can i ask for help  thanks

**Comment by andrewscofield** [comment]
The only thing I can I think that might not work for you is server isn't being allowed to use CURL with SSL.

**Comment by maiorano84** [comment]
I ran into a similar issue and it took me a bit to find out what was causing it. If you go into the parseRestClient Class and find the following CURL settings:

```
curl_setopt($c, CURLOPT_TIMEOUT, 30);
curl_setopt($c, CURLOPT_USERAGENT, 'parse.com-php-library/2.0');
curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
curl_setopt($c, CURLINFO_HEADER_OUT, true);`
```

And add this line: `curl_setopt($c, CURLOPT_SSL_VERIFYPEER, false);` that SHOULD solve some problems.

**Comment by andrewscofield** [comment]
Its true this could fix your problem, but it could also cause some security issues, so I probably won't add this line to the library for now. I'll investigate more though.

**Comment by oswowen** [comment]
I meet the same problem with marcpar and well solved by maiorano84's method. 
But then I tried to open test.php and it says: Fatal error: Uncaught ParseLibraryException: [115]: parse.com error: To push to iOS devices, you must first configure a valid certificate. thrown in C:\xampp\htdocs\parse.com-php-library-master\parse.php on line 183. 
I am a beginner. I want this parse.com-php-library-master to work as my android app back-end. So much appreciate for your answer.
