### ISSUE TITLE
whereRegex shoots out a bad special key error

### ISSUE THREAD

**Issue by liorwn** [andrewscofield/parse.com-php-library#51]
Hey,

Seems like there's a slight issue with the whereRegex function.

It always passes $options=' ' and Parse shoots out this error:
"Uncaught ParseLibraryException: [102]: parse.com error: bad special key: options "

If I comment out the 'options' => $options part it seems to work (I guess Parse doesn't like empty values there if you pass it).

Maybe this should be like this instead (there's probably a better way :) - 

public function whereRegex($key,$value,$options){
        if(isset($key) && isset($value)){
            $this->_query[$key] = array(
                '$regex' => $value,
                                if (isset($options)) {
                    'options' => $options
                                }
            );
        }  
        else{
            $this->throwError('the $key and $value parameters must be set when setting a "where" query method');  
        }

**Comment by FredvanRijswijk** [comment]
Your code give me an other error

`Parse error: syntax error, unexpected T_IF, expecting ')' in /home/xx/public_html/dev/parse/parseQuery.php on line 237`

PS, Don't know an other way to solve this, if I'm using the test is also gives me errors...

**Comment by andrewscofield** [comment]
There was a small typo in the code liorwn provided, but otherwise, it is a great fix! Thanks!

**Comment by FredvanRijswijk** [comment]
Changed the code, but still get `Uncaught ParseLibraryException: [102]: parse.com error: bad special key: options thrown in /home/xxx/public_html/dev/parse/parse.php on line 170` error

`$parseQuery->whereRegex('name', '^\d{1,5}(\.\d{1,2})?$');`

using the test example?

**Comment by andrewscofield** [comment]
Yea, sorry I found one more error after my last push. About to commit another fix in a few
