### ISSUE TITLE
How to display results?

### ISSUE THREAD

**Issue by FredvanRijswijk** [andrewscofield/parse.com-php-library#52]
Hi,

Want to use this for my backend, iOS I get, but can somebody give me an example how to use this if I want to give a result in a table (divs)... is it json what I get if I use this code:

``` <?php

require_once('parse.php');

$parseQuery = new parseQuery('Locations');
//$parseQuery->where('STAT',1);
//$parseQuery->orderByDescending('TIME');

$parseQuery->setLimit(2);
$response3 = $parseQuery->find();

?>
```

So how I handle the $respons3 in a real world example to display the result to a user?

**Comment by andrewscofield** [comment]
Hey, did you figure this out? It would be great for future reference to post an answer/example of how to handle results from Parse.com

**Comment by FredvanRijswijk** [comment]
Yes, I'll be make a blogpost or something... but also for documentation in the wiki here... Building some real life examples.

``` <?php

        $parseQuery = new parseQuery('Locations');
        $results = $parseQuery->find();

        echo '
        <table class="table table-hover">
        <thead>
         <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Published</th>
         </tr>
        </thead>
        <tbody>
        ';

        foreach( $results->{'results'} as $obj )
        {
            echo '<tr>
                    <td>' .$obj->{'name'}. '</td>
                    <td>' .$obj->{'address'}. '</td>
                    <td>' .$obj->{'published'}. '</td>
                  </tr>';
        }   

        echo '

        </tbody>
        </table>';
        ?>
```

Dirty, but it's working for now.

**Comment by liorwn** [comment]
It's probably not the best way to do it, but I find it comfortable for my purposes.

I added this function to class which converts objects to arrays (the response you get from Parse is an stdClass object):

function object_to_array($var) {
    $result = array();
    $references = array();
    foreach ($var as $key => $value) {
        // recursively convert objects
        if (is_object($value) || is_array($value)) {
            // but prevent cycles
            if (!in_array($value, $references)) {
                $result[$key] = object_to_array($value);
                $references[] = $value;
            }
        } else {
            // simple values are untouched
            $result[$key] = $value;
        }
    }
    return $result;
}

And then, following the example you started with, I do this:

$responseArray = object_to_array($response3);

And then I just foreach through the responses like so:

foreach($responseArray['results'] as $val)
{

   echo $val['STREET'];

}

Let's say you have a column in your 'Locations' table like you mentioned in the example that is named 'STREET' then you can access that specific record like above.

Hope this helps a bit!

I should mention that I need an array for my uses, you can just as well foreach the original object itself.

**Comment by andrewscofield** [comment]
Thanks guys... any example are much needed! I will try to spend some time soon to develop docs for this repo but any help is great.

I should note too that according to this: 

http://stackoverflow.com/questions/4345554/convert-php-object-to-associative-array 

you might not need that object_to_array function at all. In the case of parse responses, they are simple enough to just typecast them and it will convert them.

**Comment by liorwn** [comment]
Oh man - that's great! Should've thought of that

**Comment by andrewscofield** [comment]
I think a lot of people have the same reaction when they first see this answer... I know I did!
