### ISSUE TITLE
how to pass config parameters to class?

### ISSUE THREAD

**Issue by marckula** [andrewscofield/parse.com-php-library#53]
we have separate applications defined in Parse for our staging and development environments.  in V1 of this library, we could pass the configuration paramaters when instantiating the parseRestClient class.  This feature appears to be removed from V2 in favor of a configuration file.

Any suggestions?

**Comment by FredvanRijswijk** [comment]
`````` <?php

class parseConfig{

    const APPID = '';
    const MASTERKEY = '';
    const RESTKEY = '';
    const PARSEURL = 'https://api.parse.com/1/';
}

?>```
``````

**Comment by andrewscofield** [comment]
This scenario is exactly why I switched to a config file. Production, staging and dev environments can all have different parseConfig.php in each environment. This way you don't have to change your code when going from one environment to another.

**Comment by marckula** [comment]
We use zend framework and store all our config options in a single application.ini file for prod, stage and dev.  zend allows us to dynamically load config params based on SERVER_NAME env var.

Its convenient to be able to instantiate a class by passing config params.
