### ISSUE TITLE
Upload a file for a new object/update object

### ISSUE THREAD

**Issue by FredvanRijswijk** [andrewscofield/parse.com-php-library#54]
How can I upload a image while I make a new Object? I see that the image column is updated but the file is Acces Denied? 

Is there somebody that have done this and want to share some example code?

```
//File must contain only name, url and __type properties
                    //$parse->image = array("__type" => "File", "name" => $_FILES['cImage']['name'], 'url' => 'http://url.com/images/musea/'.$_FILES['cImage']['name']);

                    //$parse = new parseFile();
                    //$filename = 'http://url.com/images/musea/'.$_FILES['cImage']['name'];

                    //$parse = new parseFile('Locations');
                    //$file = parseFile('image/jpeg', file_get_contents($filename));
                    //$parse->image = $file->save('testimage.jpg'); //should return url and name

```

**Comment by FredvanRijswijk** [comment]
I'm really need some help with this...

**Comment by andrewscofield** [comment]
Sorry, just saw this. I'm trying to figure out where its failing for you. So, does it seem like the file is uploading correctly? Are you getting a url back from parse.com? And when you access that url through a browser its giving you a access denied? Is this correct?

**Comment by FredvanRijswijk** [comment]
Yes, it's giving me a URL that's says access denied! 

I saw that you only can use binary data... Just can't figure it out...

How to use it in a form and save it with an object at the same time or apart, it's keeps me busy for a couple of days now...

**Comment by andrewscofield** [comment]
Well, ok the above code is a little messed up. You should have something more like this for what you are trying to do:

```
//first you have to get a return from parse before associating with any objects
$filename = 'http://url.com/images/musea/'.$_FILES['cImage']['name'];
$file = new parseFile('image/jpeg', file_get_contents($filename));
$fileReturn = $file->save('testimage.jpg');

//then you create your parseObject or 
//update an existing object by using the update($objectId) method instead of save()
$parse = new parseObject('Locations');
$parse->image = $parse->dataType('file', array( $fileReturn['name'] );
$parse->save();

```

Can you please try the above and see what results you are getting. If you are still getting access denied, can you send me the exact output you get from $fileReturn?

**Comment by FredvanRijswijk** [comment]
$fileReturn is ok now, getting an error on `Fatal error: Cannot use object of type stdClass as array` on `$parse->image = $parse->dataType('file', array( $fileReturn['name'] ));`

**Comment by andrewscofield** [comment]
Oh, yes my mistake... that line should be:

```
$parse->image = $parse->dataType('file', array( $fileReturn->name ));
```

I was accessing $fileReturn as an array, when I should have been accessing it as an object

**Comment by FredvanRijswijk** [comment]
WOw stupid me, almost had the same code before... But getting errors is so frustrating and thinking I was wrong, it's WORKING! Thnx!!!

**Comment by andrewscofield** [comment]
Great to hear!

**Comment by luisbatista** [comment]
Great, is what I need to upload my images and connect with objects.
