### ISSUE TITLE
getCount is missing Limit = 0

### ISSUE THREAD

**Issue by FredvanRijswijk** [andrewscofield/parse.com-php-library#55]
If you are limiting your query, or if there are a very large number of results, and you want to know how many total results there are without returning them all, you can use the count parameter. For example, if you only care about the number of games played by a particular player:

```

curl -X GET \
  -H "X-Parse-Application-Id: ucucfdUq3EpDau0cOTPGDl5EKepBYmLlJpNoXKdo" \
  -H "X-Parse-REST-API-Key: sysqIYFSGV6KzCczu1amCs3iTWnukJC8vGu0Li9r" \
  -G \
  --data-urlencode 'where={"playerName":"Jonathan Walsh"}' \
  --data-urlencode 'count=1' \
  --data-urlencode 'limit=0' \
  https://api.parse.com/1/classes/GameScore

```

Adding a setLimit(0) is not possible, but if you want to make a dashboard it's very slow, because the reason above says it's also getting all the data...

**Comment by FredvanRijswijk** [comment]
Solved this woth this code in parseQuery.php

line 45

```
if($this->_count == 1){
            $urlParams['count'] = '1';
            $urlParams['limit'] = '0';
        }
```

and

line 59:

```
public function getCount(){
        $this->_count = 1;
        $this->_limit = 0;
        return $this->find();
    }

```

**Comment by warnew** [comment]
You created a a problem, not solved one. Now you have to use two request for counting and displaying results, wasting one.
