### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by the-vesuvius** [andrewscofield/parse.com-php-library#56]
Hi!
Your lib is really helpful. Thank you for your work :)

But I have a question:
Can your lib work with roles?

**Comment by andrewscofield** [comment]
I haven't had a chance to do roles yet :( Any ideas or thoughts on how
to implement it, I haven't had a need for them in parse.com yet.

Andrew

**Comment by the-vesuvius** [comment]
Sorry, but I haven't any thoughts on how to implement roles yet. I'm new to Parse.com, so your lib also helps me to understand this service :)

**Comment by jobrienski** [comment]
I'm working on it now.  Extending the "parseObject" class.  It's not much different than an object.

**Comment by andrewscofield** [comment]
Awesome, thanks man!

**Comment by jobrienski** [comment]
No problemo - I really needed it.
https://github.com/apotropaic/parse.com-php-library/pull/59
