### ISSUE TITLE
parseUser suggestion for reset password throught parse mail

### ISSUE THREAD

**Issue by StefanoJ** [andrewscofield/parse.com-php-library#60]
It coudl be nice if you can ask for password reset usign this library..
I've added this code at your userParse.php:

```
public function requestPasswordReset($email){
    if(!empty($email)){
        $request = $this->request(array(
                'method' => 'POST',
                'requestUrl' => 'requestPasswordReset',
                'email' => $email,
                'data' => $this->data
        ));

        return $request;
    }
    else{
        $this->throwError('email is required for the requestPasswordReset method');
    }

}
```

This way it throws a Parse: ParseLibraryException: [107]: parse.com error: invalid json: null
But the Parse response is a null json if it's all correct... I think this will create a bit of confusion..

Can you help me to make it works in your library?

**Comment by andrewscofield** [comment]
I agree it would be nice to add this method. I think the error is actually in that you aren't setting the email before you send it. I'll add that in a send add this method to the library.
