### ISSUE TITLE
(Urgent) Problem getting the parse Test to run

### ISSUE THREAD

**Issue by arkangelx** [andrewscofield/parse.com-php-library#61]
I have downloaded and installed the  parse library  trying to learn to use it. There are issues running the most basic of tests offered by the code provided.. 

Fatal error: Uncaught ParseLibraryException: [102]: parse.com error: $regex: only works on string fields thrown in /var/www/urls/cft_access/services/parse.php on line 169

if its any help, this is the link to it..please advise

http://www.mobileparadigm.co.uk/urls/cft_access/services/test.php

**Comment by andrewscofield** [comment]
Hey it looks like the problem is that parse.com changed their regex parameter to only allow regex on strings. I've updated the tests to test regex against a string instead.

**Comment by arkangelx** [comment]
Erm dude.. it doesn't work..sorry. I noticed that you updated the ParseLibraryException in the parse.php file. However I downloaded the entire set of class again just to be sure.
KInd regards

http://www.mobileparadigm.co.uk/urls/cft_access/services/parse_lib/test.php

**Comment by FredvanRijswijk** [comment]
What is your Query? It work fine by me...

**Comment by arkangelx** [comment]
please execute this link 
http://www.mobileparadigm.co.uk/urls/cft_access/services/parse_lib/test.php

**Comment by andrewscofield** [comment]
Yea, you'll notice this error is different then the one you posted. After I
fixed the one mentioned this one came up. Still working on a fix for the
$inquery method.

I hadn't run tests for a few months until you mentioned having problems. It
seems parse has changed some stuff related to their queries. For example,
if you got to parse.com/docs/rest and try and find mention of the regex
query option. It seems to have vanished, yet they now only allow strings to
be used in regex query.
