### ISSUE TITLE
User, Product Classes returning nothing.

### ISSUE THREAD

**Issue by thedangler** [andrewscofield/parse.com-php-library#63]
I don't know if this is happening to everyone or just me, but I am having trouble getting results back from the User class.  It always returns nothing.

$query = new parseQuery("Email");
$query->where('serialized_data',$_GET['id']);
$result = $query->find();
print_r($result); // returns proper result

$query_user = new parseQuery("User");
$query_user->where('objectId',"kHnpx7lBmF");
print_r($query_user->find()); // returns nothing.  Should return the User

I've checked the objectId 10 times, the information is correct.
the User Class doesn't have any ACL on it either.

Is there something i'm missing?

**Comment by thedangler** [comment]
No one has this problem?

**Comment by andrewscofield** [comment]
Sorry I'm just now seeing this. Try updating your code to this:

```
$query_user = new parseQuery('users');
$query_user->where('objectId',"kHnpx7lBmF");
print_r($query_user->find());
```

The difference being 'users' versus 'User' when initializing the query object.

Let me know if that works.

**Comment by thedangler** [comment]
Does this user the User class in parse or does it make a new classes called
users?

**Comment by andrewscofield** [comment]
It causes the API call to go to /1/users  instead of /1/classes/user like it was doing when were excluding the 's'

Hope that makes sense.
