### ISSUE TITLE
PHP Notice:  Trying to get property of non-object

### ISSUE THREAD

**Issue by jonerickson** [andrewscofield/parse.com-php-library#67]
For the life of me I cannot get the parse library to work. For some reason it will not work on my Windows Machine with WAMP or XAMPP but on my MAC with MAMP, it works perfectly fine. Every time the function request is called in parse.php, something fails and it leaves $response as false and $responseCode as 0. My parseConfig.php is properly configured and this is the code I am using that works fine on my MAC but doesnt on windows. Can someone give a little insight?

```
    $parse = new parseQuery($class = 'PushNotifications');
    $parse->whereEqualTo('unit', $unit);
    $result = $parse->find();
```

**Comment by andrewscofield** [comment]
Can you check an error log maybe? A common cause of $response being false and $responseCode 0 is curl compatible

**Comment by jonerickson** [comment]
So I replaced...

```
$response = curl_exec($c); 
```

with

```
if( ! $response = curl_exec($c) ) {
die(curl_error($c));
} 
```

and it printed this error: SSL certificate problem: unable to get local issuer certificate.

I have no idea where the problem is coming from so I added the following and it works fine now.

```
curl_setopt($c, CURLOPT_SSL_VERIFYPEER, FALSE);
```

**Comment by andrewscofield** [comment]
Yea a lot of people seem to have issues with curl and SSL. I'll verify with parse and find out if we really need to have it on. If we don't I'll implement this into the library.

**Comment by blak3r** [comment]
@JonErickson See the pull request I just submitted. I think it'll solve your issue.

**Comment by jonerickson** [comment]
Awesome, thanks!

**Comment by andrewscofield** [comment]
@blak3r thanks! After some investigating it seem that HTTPS is required, so you're pull request could be key to helping all these people who seem to be having certificate problems. I'll do some digging around to make sure its not going to break all other users.
