### ISSUE TITLE
More Code Examples

### ISSUE THREAD

**Issue by rbreve** [andrewscofield/parse.com-php-library#72]
Could you add more code examples, for example basic queries? thanks

**Comment by andrewscofield** [comment]
Hey have you checked out the tests folder? In there I have a whole bunch of example basic queries:

https://github.com/apotropaic/parse.com-php-library/blob/master/tests/parseQueryTest.php

**Comment by iantearle** [comment]
I dont think its totally clear how you would run the example, or how you would integrate with a GUI? I'm guessing you just hit the the example pages and each functions runs the queries, or sends the push if I load parsePushTest.php in my browser?

**Comment by andrewscofield** [comment]
No, you can run test.php in your browser to execute the tests. But that's more for me then anything to make sure the library works. But you can use the tests contained in the test folder as examples for you to see how the code is supposed to work. No real need to execute them. You are better off copying the code and playing around with it to understand how it works.

**Comment by rbreve** [comment]
I'll take a look at it , thanks
