### ISSUE TITLE
Push Time

### ISSUE THREAD

**Issue by iantearle** [andrewscofield/parse.com-php-library#73]
push_time is available in the REST api, is it available in this library? I couldn't see anything in the example parsePushTest.php, not even commented?

**Comment by andrewscofield** [comment]
Could you provide a link to the push_time parameter? I don't know how new it is but I haven't seen it. I did however make this library ready for new parameters even if I don't know about them. Check out the parsePushTest.php source code.  Lines 17-28 are the parameters that were documented at the time I wrote the test file. But there is no reason you couldn't on line 29 add:

```
$parsePush->push_time = //whatever format data this parameter requires
```

**Comment by iantearle** [comment]
Hi, yes https://www.parse.com/docs/push_guide#scheduled/REST shall try adding that line in an giving it a try.

Thanks.

**Comment by iantearle** [comment]
Works. Meant to close this a while ago.
