### ISSUE TITLE
Case Sensitive Search

### ISSUE THREAD

**Issue by ghost** [andrewscofield/parse.com-php-library#74]
Hi,

Can anyone help me for case sensitive search. as i have to search by using any case 'Upper' or 'Lower'

Thanks,

**Comment by andrewscofield** [comment]
Do you know if this is even possible on the parse.com side of things? Have you checked out their rest docs? https://parse.com/docs/rest

I would start there to see if this is something they even support.

**Comment by ghost** [comment]
Thanks...

i just got the solution only in regex we have to give "Options" attribute to "im" and regex to meed the need i mentioned in the question.

Thanks,
Shahid
