### ISSUE TITLE
Inner queries - are they possible?

### ISSUE THREAD

**Issue by ghost** [andrewscofield/parse.com-php-library#75]
Lets say I have two tables, one of fruit (e.g. orange) and one of fruit type (e.g. citrus) - The fruit table contains a pointer column pointing to the fruit type. I want to do a query similar to the following: return all fruit of a specific type.

In javascript you can just use matchesQuery() or query.include(). Is there an  equivalent in this library?

**Comment by ghost** [comment]
Any ideas?

**Comment by andrewscofield** [comment]
Can you show me some examples from the REST docs on parse.com so I know what you are talking about exactly? If you can't find it in the REST docs, the answer is most certainly no.

**Comment by ghost** [comment]
I think the following covers what I need:

When retrieving objects that have pointers to children, you can fetch child objects by using the include option. For instance, to fetch the object pointed to by the "game" key:
curl -X GET \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -G \
  --data-urlencode 'include=game' \
  https://api.parse.com/1/classes/GameScore/Ed1nuqPvcm

**Comment by ghost** [comment]
Never mind, I've found the function I wanted but thanks for the help:

```
public function whereInclude($value){
        if(is_string($value)){
            $this->_include[] = $value;
        }
        else{
            $this->throwError('the include parameter on parseQuery must be a string');
        }
    }
```
