### ISSUE TITLE
Fetch all records in a table

### ISSUE THREAD

**Issue by ghost** [andrewscofield/parse.com-php-library#76]
I want to create a query that returns all the rows within a table without any need for restricting the query. Currently if I do this,  a 'No query set yet' error is thrown.

**Comment by andrewscofield** [comment]
Could you provide some code for me to check out? Maybe we can come up with something to make this work

**Comment by ghost** [comment]
Here's the code:

```
    $parseQuery = new parseQuery('Job');
    $results = json_encode($parseQuery->find());
    $results = json_decode($results,true);
```

I know it shouldn't need the json_encode/decode, but doesn't return json correctly unless I do that; the problem I really need to fix is fetching a table's complete contents.

**Comment by andrewscofield** [comment]
Yea I don't really see a way to do this. Let me see what I can do to make that possible. Your code makes sense and should work, so I'll try to make that be how it works.

**Comment by andrewscofield** [comment]
fixed this here: https://github.com/apotropaic/parse.com-php-library/commit/a3d1c1f03f6cc8de8f12c1156afc3813a03ccc45
