### ISSUE TITLE
facebook/twitter

### ISSUE THREAD

**Issue by ghost** [andrewscofield/parse.com-php-library#77]
Is there any way to sign up a new user with provided facebook/twitter auth data only (i.e. no password/username, purely through either facebook or twitter credentials)? I'm not entirely sure if the API supports this or not.

I only ask because there is no support for twitter in the parse javascript API; I want to be able to use both services via PHP so things aren't mixed up.

**Comment by andrewscofield** [comment]
It seems this is possible with the REST API, but not this library. Tou can link an existing account with a social account using auth data. 

 It wouldn't be too difficult to do, I should be able to implement this in a couple days.

**Comment by elistone** [comment]
Hey,

Whats the lastest on this being put into the library?

**Comment by andrewscofield** [comment]
Just need to find time. I'll try this weekend and will update this post when I get it done.

**Comment by andrewscofield** [comment]
ugh, sorry got too busy with work this weekend. I will keep you all post though.

**Comment by elistone** [comment]
Thats alright, I got it working for myself anyway but might be useful for other people.

**Comment by andrewscofield** [comment]
Yea it would. Do you have source code to share that I could throw into the
library?

**Comment by elistone** [comment]
So I created a function in parseUser.php called socialLogin

```
public function socialLogin(){
    if(!empty($this->authData)){
        $request = $this->request( array(
            'method' => 'POST',
            'requestUrl' => 'users',
            'data' => array(
                'authData' => $this->authData
            )
        ));

        return $request;    
    }else{
        $this->throwError('authArray must be set use addAuthData method');
    }
}
```

Then had to update parse.php $expectedCode to be an array so it would include the call back of both '200' (success) and '201' (updated) 

```
      // Line 104
    $expectedCode = array('200');
    if($args['method'] == 'POST' && substr($args['requestUrl'],0,4) != 'push'){
        $expectedCode = array('201','200');
    }

       // Line 193
      if(!in_array($responseCode,$expectedCode)){
        $error = json_decode($response);
            $this->throwError($error->error,$error->code);
    }
```

Not sure if this is the best way to do it, but it works fine for me.

**Comment by ghost** [comment]
Could you be a bit more specific about what lines you've edited/replaced/inserted, etc.

**Comment by elistone** [comment]
I shall try to explain a little better...

but please keep in mind I am not sure this is the best way to do it or if it brakes anything else as i have not complete tested it but for more it is still working...

Although everything still seems to be working for me.

### parseUser.php

in parseUser.php add this function:

```
public function socialLogin(){
   if(!empty($this->authData)){
      $request = $this->request( array(
          'method' => 'POST',
          'requestUrl' => 'users',
            'data' => array(
              'authData' => $this->authData
        )
    ));
    return $request;    
}else{
    $this->throwError('authArray must be set use addAuthData method');
}
}
```

### parse.php

in parse.php line **106 - 109** replace:

```
    $expectedCode = '200';
    if($args['method'] == 'POST' && substr($args['requestUrl'],0,4) != 'push'){
        $expectedCode = '201';
    }
```

With _(changes expectedCode from a number to an array of numbers)_:

```
    $expectedCode = array('200');
    if($args['method'] == 'POST' && substr($args['requestUrl'],0,4) != 'push'){
        $expectedCode = array('201','200');
    }
```

Then in the checkResponse function line **180 - 196**
Replace: 

```
        if($responseCode != $expectedCode){
        $error = json_decode($response);
        $this->throwError($error->error,$error->code);
    }
```

with _(makes a check to see if the responceCode is found in the array)_:

```
    if(!in_array($responseCode,$expectedCode)){
        $error = json_decode($response);
        $this->throwError($error->error,$error->code);
    }
```

and lastly not as important but useful for debugging line **111 - 115** replace:

```
    if($expectedCode != $responseCode){
        //BELOW HELPS WITH DEBUGGING
        //print_r($response);
        //print_r($args);       
    }
```

With:

```
    if(!in_array($responseCode,$expectedCode)){
        //BELOW HELPS WITH DEBUGGING
        //print_r($response);
        //print_r($args);       
    }
```

Hope that explains it better.
Eli
