### ISSUE TITLE
multiple constraints on query

### ISSUE THREAD

**Issue by jonerickson** [andrewscofield/parse.com-php-library#78]
I am looking for a way to do a query with multiple constraints. Is this possible in this library? Basically I want to check 2 sets of key/value, not one key for multiple values, but two different keys expecting 2 different values. thanks.

**Comment by andrewscofield** [comment]
You sure can... just keep stacking up the queries you want: 

```
$parseQuery = $this->parseQuery;
$parseQuery->where('first_name','Foo');
$parseQuery->where('last_name','Bar');
$return = $parseQuery->find();
```

Next time I have a window for feature/upgrades I will make them chainable like so:

```
$parseQuery = $this->parseQuery;
$parseQuery->where('name','Foo')->where('last_name','Bar');
$return = $parseQuery->find();
```

Maybe even accept an array as well?

Let me know if that doesn't work for you
