### ISSUE TITLE
Push Send everyone

### ISSUE THREAD

**Issue by lsantaniello** [andrewscofield/parse.com-php-library#84]
Hi all,

I need use php API to send push notification but I have problems.

I downloaded parse.com-php-library and copied it into my web server.

try {

```
$ch = curl_init();

$arr = array();
array_push($arr, "X-Parse-Application-Id: " . parseConfig::APPID);
array_push($arr, "X-Parse-REST-API-Key: " . parseConfig::RESTKEY);
array_push($arr, "Content-Type: application/json");

$req = '{ "channel": "", data": { "alert": "Test!" } }';

curl_setopt($ch, CURLOPT_HTTPHEADER, $arr);
curl_setopt($ch, CURLOPT_URL, 'https://api.parse.com/1/push');
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $req);

curl_exec($ch);
curl_close($ch);
```

} catch (Exception $ex) {
    echo "..................." . $ex->getMessage();
}

How can I create json request to sent push at ios or android devices?

Thanks

**Comment by andrewscofield** [comment]
There are some examples on how to use push with this library here:

https://github.com/apotropaic/parse.com-php-library/blob/master/tests/parsePushTest.php
