### ISSUE TITLE
ERROR: response code was 401 with message: unauthorized

### ISSUE THREAD

**Issue by ldjpr** [andrewscofield/parse.com-php-library#9]
I have updated to latest version and started receiving the mentioned error. The reason for it is that following option was eliminated  from request function.

curl_setopt($c, CURLOPT_USERPWD,  $this->appid . ':' . $this->restkey);

I can see that the intention is to pass these in the header:

curl_setopt($c, CURLOPT_HTTPHEADER, array(
                    'Content-Type: application/json',
                    'X-Parse-Application-Id: '.$this->appid,
                    'X-Parse-REST-API-Key: '.$this->restkey
        ));

Is this working for anyone? And if yes any pointers why it might not be working on my side?

thanks

**Comment by andrewscofield** [comment]
Yea, parse change the method of authentication. See here: http://parse.com/docs/rest#general-requests

So, I updated the library to work accordingly. Along with this change, they introduced a REST api key, where before you might have been using what they called their master api key. That could be the problem if you are getting 'unauthorized' message. Check your parse dashboard to verify you are using the rest api key and let me know how it goes.

**Comment by ldjpr** [comment]
Yeap. Totally right. Replaced with new restkey and it worked. 

Thanks
