### ISSUE TITLE
Compound Queries

### ISSUE THREAD

**Issue by elistone** [andrewscofield/parse.com-php-library#91]
Is there anyway to do Compound Queries?

> If you want to find objects that match one of several queries, you can use $or operator, with a JSONArray as its value. For instance, if you want to find players with either have a lot of wins or a few wins.

https://parse.com/docs/rest#queries-compound

Eli

**Comment by andrewscofield** [comment]
Something like this should work. I will mark this issue as a todo item because this should really be easier and figure out a function to make this more straight forward

```
$compoundQuery = array(
    array('wins' => array('$gt' => '150')),
    array('wins' => array('$lt' => '5'))
));

$parseQuery = new parseQuery('Player');
$parseQuery->where('$or', $compoundQuery);
$return = $parseQuery->find();
```
